spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shawnpei
    username: postgres
    password: password
  profiles:
    active: dev
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
    include-binding-errors: always
