spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shawnpei
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    include: dev
    active: dev

server:
  error:
    include-message: always
    include-binding-errors: always
