name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 15.4
  POSTGRESQL_DB: shawnpei
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 17

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          postgres:
            image:
              postgres:15.4
            env:
              POSTGRES_DB: shawnpei
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: password
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v2
            with:
              java-version: 17
              distribution: 'adopt'
          - name: Maven Clean Package
            run:
              mvn --no-transfer-progress clean package -P build-frontend